language: node_js
node_js:
  - "stable"
cache:
  directories:
  - my-app/node_modules
script:
  - cd ./my-app
  - yarn test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master